# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Jason DiBiase
tagline:          Research notes on volatility, options, models and things I have been interested in
description:      This is my own personal blog where I post my current reseach and projects ranging from insights about options markets, computer programming and volatility. 
sidebar_text:     Personal research, projects and code.
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           Jason DiBiase
  url:            https://www.linkedin.com/in/jasondibiase/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
